### ISSUE TITLE
Import / Export Functionality

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/admin-menu-manager#26]
[Reported](https://wordpress.org/support/topic/feature-suggestion-export-and-import) by @fgilio on the WordPress.org support forums:

> One useful feature I imagine is the ability to export/import menu profiles. And maybe one option to export it directly to php, very dev friendly.

Not sure how difficult it would be to implement such a feature.

For example, when you have plugin X on site A, but not on site B, what happens when you import the menu settings from one site to the other? It would probably be added to the site (after #3), but resulting in a 404...

A simple JSON import / export would probably be needed for #25.

**Comment by fgilio** [comment]
Yes, there are some considerations that would be needed. I must admit that I didn't think of all of them when doing the suggestion. Still think it would be a great addition, but it would require some work.

The system would have to check if there is already X menu entry before applying the imported profile. For each non standard menu item, or maybe just all for simplicity.
Then it could alert about the incompatibility and stop there. Or just make a disabled entry that acts like a placeholder for when the corresponding plugin is activated.
You would have to hook into and activate plugin kind of hook, right? So that you don't have to check at every page refresh.

Maybe it's just to complicated too be worth it?

PD: Moving the config to the user meta seems like an awesome move!

**Comment by swissspidy** [comment]
I think the basic import / export functionality works quite well at the moment.

You're probably on your own when importing a complete menu with items that don't exist on the other site. We should warn the user about the consequences and not fail completely when something like this happens.

**Comment by swissspidy** [comment]
Closing for now. Can create new issues when bugs pop up.
