### ISSUE TITLE
Allow adding custom menu items

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/admin-menu-manager#3]
There could be an "Add" button (with a small plus icon? :)) that lets users add a custom menu item with label, icon and URL.

Obviously, adding separators should be possible too.

**Comment by swissspidy** [comment]
There are many edge-cases to be considered for this.
- Who needs custom items and not just separators?
- Where should they link to? Permissions? Classes?
- Language?

See how other plugins are doing this first...

**Comment by fgilio** [comment]
The option of adding separators will be great to help keep order and separation of concerns in menu zones. This is a big problem in scenarios when you have lots of plugin menus (not that you should install lots of plugins, but that's another topic in itself) splattered all around the menu sidebar, which happens too often.

But giving a second thought around custom menu items, it find it just too good. For some reason I didn't think of external links at first sight.
You could add entry for external services, things like Analytics, Pushwoosh, the sites Facebook App dev page, and so on. And even put all them inside a "External" parent entry.
Yes this would need some kind of Permission check. Personally I find it more useful and straight forward when choosing from a list of users levels (admin, editor, subscriber) instead of plain capabilities. The majority of time I don't need that kind of fine grained control.

PD: I just can't stop finding uses for this plugin. Albeit the majority require adding features, and code...

Congrats, you have something awesome here. Keep the good work!
