### ISSUE TITLE
Activated and plugin doesn't appear to be doing anything

### ISSUE THREAD

**Issue by JasonTheAdams** [wearerequired/admin-menu-manager#42]
Possibly related to #41

After activating the plugin it doesn't appear to be doing anything. I'm looking for a menu somewhere, the edit button, or something. I'm not seeing anything. Am I missing something? :)

**Comment by swissspidy** [comment]
Hey there,

Thank you very much for testing the latest development version of our plugin from GitHub.

The thing is, in contrast to the current version [available from WordPress.org](https://wordpress.org/plugins/admin-menu-manager/), the GitHub repository only contains the _source_ files needed to build the actual plugin. That means nothing happens when you try to activate that plugin in your WordPress admin because scripts and styles are missing.

So when you check out the repository or download the ZIP archive, you need to use `grunt` to build CSS files from the Sass files and to combine all the JavaScript modules.
1. Run `npm install` (you need [Node.js](https://nodejs.org/en/) for that) to install Grunt and its dependencies
2. Run `grunt` to achieve this, or `grunt build` to get a ZIP file that you could upload to your WordPress site.

If you wanna skip that, I just ran these commands and uploaded that final ZIP file here: https://cloudup.com/ca7r5J5tKRJ. Happy testing!

**Comment by JasonTheAdams** [comment]
Bah, I just wasn't thinking. Hahah! Thanks for the gracious "duh". :)
