### ISSUE TITLE
Fatal error: Class 'WP_Requirements_Check' not found

### ISSUE THREAD

**Issue by NickHeurter** [wearerequired/admin-menu-manager#48]
When I try to active plugin version 2.0 of the plugin on my Wordpress 4.8 installation I receive the following error: 

`Fatal error: Class 'WP_Requirements_Check' not found in /wp-content/plugins/admin-menu-manager-master/admin-menu-manager.php on line 38`

How to fix this so I can use version 2.0 of the plugin?

**Comment by swissspidy** [comment]
Hey there,

Did you use the version from WordPress.org or the one on GitHub? For the latter, you need to run `composer install` first. And then `npm install && grunt` to generate all the CSS and JS.

If you don't want to do that, you can download the 2.0 beta version from WordPress.org like so:

1. Visit https://wordpress.org/plugins/admin-menu-manager/
2. Click on _Advanced View_ in the sidebar
3. Scroll to the bottom and click _Download_ next to _Development Version_

**Comment by NickHeurter** [comment]
Hey there,

Thanks for your fast reply. I've tried to install trough the _Advanced View_ in de sidebar of the plugin, but after downloading and installation the version seems to be `Version: 1.0.3`

What am I doing wrong?

**Comment by swissspidy** [comment]
Ugh, that's my fault, sorry. Since it's an _alpha_ version and not yet a beta, I apparently didn't it upload on WordPress.org just yet.

I just created a new [2.0.0-alpha release](https://github.com/wearerequired/admin-menu-manager/releases/tag/2.0.0-alpha) for you here on GitHub so you can download it from here.

Direct download: https://github.com/wearerequired/admin-menu-manager/releases/download/2.0.0-alpha/admin-menu-manager.zip

**Comment by NickHeurter** [comment]
Awesome, thanks a lot @swissspidy! I've installed it and I will start testing it. If I run into any issue I will let you know!
